# Generated by Django 5.2.1 on 2025-05-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorial',
            name='pais',
            field=models.CharField(default='No Registra', max_length=100),
        ),
        migrations.AddField(
            model_name='resena',
            name='puntuacion',
            field=models.IntegerField(default=0),
        ),
    ]
